package com.backend.gbp.domain.enums;

public enum UserActivityType {
    VERIFY_SKETCH_PLAN,
    APPROVE_BL_PLAN,
    APPROVE_DENR_PLAN,
    APPROVE_LOT_TRANSACTION,
    APPROVE_SKETCH_PLAN,
    TRANSMIT_BL_PLAN,
    TRANSMIT_DENR_SKETCH_PLAN,
    TRANSMIT_SKETCH_PLAN,
    MANAGE_PENDING_LOT_TRANSACTION,
    RELEASE_APPROVED_PLAN,
    RELEASE_SKETCH_PLAN,
    SIGN_APPROVED_PLAN,
    TRANSMIT_LDC_AND_CAD_MAP,
    VERIFY_BL_PLAN,
    VERIFY_SIGNED_APPROVED_PLAN,
}
