export const dummySelectedEmployeesByDept = [
  {
    department: '0',
    departmentName: 'department one',
    data: [
      {
        id: 101,
        fullName: 'Employee One',
        department: { id: '0', departmentName: 'department one' },
      },
      {
        id: 111,
        fullName: 'Employee Two',
        department: { id: '0', departmentName: 'department one' },
      },
      {
        id: 222,
        fullName: 'Employee Three',
        department: { id: '0', departmentName: 'department one' },
      },
    ],
  },

  {
    department: '1',
    departmentName: 'department two',
    data: [
      {
        id: 333,
        fullName: 'Employee Four',
        department: { id: '1', departmentName: 'department two' },
      },
      {
        id: 444,
        fullName: 'Employee Five',
        department: { id: '1', departmentName: 'department two' },
      },

      {
        id: 555,
        fullName: 'Employee Six',
        department: { id: '1', departmentName: 'department two' },
      },
    ],
  },
];

export const dummyEmployeeLogs = [
  {
    id: 101,
    fullName: 'Employee One',
    department: { id: 0, departmentName: 'department one' },
    logs: [
      {
        date: 0,
        scheduleStart: 0,
        scheduleEnd: 0,
        inTime: 0,
        outTime: 0,
        message: 0,
        isError: 0,
        late: 5,
        undertime: 5,
        worked: 5,
        hoursRestDay: 5,
        hoursSpecialHoliday: 5,
        hoursSpecialHolidayAndRestDay: 5,
        hoursRegularHoliday: 5,
        hoursRegularHolidayAndRestDay: 5,
        hoursDoubleHoliday: 5,
        hoursDoubleHolidayAndRestDay: 5,
        hoursRegularOvertime: 5,
        hoursRestOvertime: 5,
        hoursSpecialHolidayOvertime: 5,
        hoursSpecialHolidayAndRestDayOvertime: 5,
        hoursRegularHolidayOvertime: 5,
        hoursRegularHolidayAndRestDayOvertime: 5,
        hoursDoubleHolidayOvertime: 5,
        hoursDoubleHolidayAndRestDayOvertime: 5,
        hoursNightDifferential: 5,
        hoursWorkedNSD: 5,
        hoursRestDayNSD: 5,
        hoursSpecialHolidayNSD: 5,
        hoursSpecialHolidayAndRestDayNSD: 5,
        hoursRegularHolidayNSD: 5,
        hoursRegularHolidayAndRestDayNSD: 5,
        hoursDoubleHolidayNSD: 5,
        hoursDoubleHolidayAndRestDayNSD: 5,
        countDoubleHolidayAndRestDay: 5,
        workedOIC: 5,
        hoursSpecialHolidayOIC: 5,
        hoursRegularHolidayOIC: 5,
        hoursDoubleHolidayOIC: 5,
        hoursRegularOICOvertime: 5,
        hoursSpecialHolidayOICOvertime: 5,
        hoursRegularHolidayOICOvertime: 5,
        hoursDoubleHolidayOICOvertime: 5,
        hoursWorkedOICNSD: 5,
        hoursSpecialHolidayOICNSD: 5,
        hoursRegularHolidayOICNSD: 5,
        hoursDoubleHolidayOICNSD: 5,
        hoursAbsent: 5,
        unallocated: 0,
      },
    ],
  },
  {
    id: 111,
    fullName: 'Employee Two',
    department: { id: 0, departmentName: 'department one' },
    logs: [
      {
        date: 0,
        scheduleStart: 0,
        scheduleEnd: 0,
        inTime: 0,
        outTime: 0,
        message: 0,
        isError: 0,
        late: 5,
        undertime: 5,
        worked: 5,
        hoursRestDay: 5,
        hoursSpecialHoliday: 5,
        hoursSpecialHolidayAndRestDay: 5,
        hoursRegularHoliday: 5,
        hoursRegularHolidayAndRestDay: 5,
        hoursDoubleHoliday: 5,
        hoursDoubleHolidayAndRestDay: 5,
        hoursRegularOvertime: 5,
        hoursRestOvertime: 5,
        hoursSpecialHolidayOvertime: 5,
        hoursSpecialHolidayAndRestDayOvertime: 5,
        hoursRegularHolidayOvertime: 5,
        hoursRegularHolidayAndRestDayOvertime: 5,
        hoursDoubleHolidayOvertime: 5,
        hoursDoubleHolidayAndRestDayOvertime: 5,
        hoursNightDifferential: 5,
        hoursWorkedNSD: 5,
        hoursRestDayNSD: 5,
        hoursSpecialHolidayNSD: 5,
        hoursSpecialHolidayAndRestDayNSD: 5,
        hoursRegularHolidayNSD: 5,
        hoursRegularHolidayAndRestDayNSD: 5,
        hoursDoubleHolidayNSD: 5,
        hoursDoubleHolidayAndRestDayNSD: 5,
        countDoubleHolidayAndRestDay: 5,
        workedOIC: 5,
        hoursSpecialHolidayOIC: 5,
        hoursRegularHolidayOIC: 5,
        hoursDoubleHolidayOIC: 5,
        hoursRegularOICOvertime: 5,
        hoursSpecialHolidayOICOvertime: 5,
        hoursRegularHolidayOICOvertime: 5,
        hoursDoubleHolidayOICOvertime: 5,
        hoursWorkedOICNSD: 5,
        hoursSpecialHolidayOICNSD: 5,
        hoursRegularHolidayOICNSD: 5,
        hoursDoubleHolidayOICNSD: 5,
        hoursAbsent: 5,
        unallocated: 0,
      },
    ],
  },
  {
    id: 222,
    fullName: 'Employee Three',
    department: { id: 0, departmentName: 'department one' },
    logs: [
      {
        date: 0,
        scheduleStart: 0,
        scheduleEnd: 0,
        inTime: 0,
        outTime: 0,
        message: 0,
        isError: 0,
        late: 5,
        undertime: 5,
        worked: 5,
        hoursRestDay: 5,
        hoursSpecialHoliday: 5,
        hoursSpecialHolidayAndRestDay: 5,
        hoursRegularHoliday: 5,
        hoursRegularHolidayAndRestDay: 5,
        hoursDoubleHoliday: 5,
        hoursDoubleHolidayAndRestDay: 5,
        hoursRegularOvertime: 5,
        hoursRestOvertime: 5,
        hoursSpecialHolidayOvertime: 5,
        hoursSpecialHolidayAndRestDayOvertime: 5,
        hoursRegularHolidayOvertime: 5,
        hoursRegularHolidayAndRestDayOvertime: 5,
        hoursDoubleHolidayOvertime: 5,
        hoursDoubleHolidayAndRestDayOvertime: 5,
        hoursNightDifferential: 5,
        hoursWorkedNSD: 5,
        hoursRestDayNSD: 5,
        hoursSpecialHolidayNSD: 5,
        hoursSpecialHolidayAndRestDayNSD: 5,
        hoursRegularHolidayNSD: 5,
        hoursRegularHolidayAndRestDayNSD: 5,
        hoursDoubleHolidayNSD: 5,
        hoursDoubleHolidayAndRestDayNSD: 5,
        countDoubleHolidayAndRestDay: 5,
        workedOIC: 5,
        hoursSpecialHolidayOIC: 5,
        hoursRegularHolidayOIC: 5,
        hoursDoubleHolidayOIC: 5,
        hoursRegularOICOvertime: 5,
        hoursSpecialHolidayOICOvertime: 5,
        hoursRegularHolidayOICOvertime: 5,
        hoursDoubleHolidayOICOvertime: 5,
        hoursWorkedOICNSD: 5,
        hoursSpecialHolidayOICNSD: 5,
        hoursRegularHolidayOICNSD: 5,
        hoursDoubleHolidayOICNSD: 5,
        hoursAbsent: 5,
        unallocated: 0,
      },
    ],
  },
  {
    id: 333,
    fullName: 'Employee Four',
    department: { id: 1, departmentName: 'department two' },
    logs: [
      {
        date: 0,
        scheduleStart: 0,
        scheduleEnd: 0,
        inTime: 0,
        outTime: 0,
        message: 0,
        isError: 0,
        late: 5,
        undertime: 5,
        worked: 5,
        hoursRestDay: 5,
        hoursSpecialHoliday: 5,
        hoursSpecialHolidayAndRestDay: 5,
        hoursRegularHoliday: 5,
        hoursRegularHolidayAndRestDay: 5,
        hoursDoubleHoliday: 5,
        hoursDoubleHolidayAndRestDay: 5,
        hoursRegularOvertime: 5,
        hoursRestOvertime: 5,
        hoursSpecialHolidayOvertime: 5,
        hoursSpecialHolidayAndRestDayOvertime: 5,
        hoursRegularHolidayOvertime: 5,
        hoursRegularHolidayAndRestDayOvertime: 5,
        hoursDoubleHolidayOvertime: 5,
        hoursDoubleHolidayAndRestDayOvertime: 5,
        hoursNightDifferential: 5,
        hoursWorkedNSD: 5,
        hoursRestDayNSD: 5,
        hoursSpecialHolidayNSD: 5,
        hoursSpecialHolidayAndRestDayNSD: 5,
        hoursRegularHolidayNSD: 5,
        hoursRegularHolidayAndRestDayNSD: 5,
        hoursDoubleHolidayNSD: 5,
        hoursDoubleHolidayAndRestDayNSD: 5,
        countDoubleHolidayAndRestDay: 5,
        workedOIC: 5,
        hoursSpecialHolidayOIC: 5,
        hoursRegularHolidayOIC: 5,
        hoursDoubleHolidayOIC: 5,
        hoursRegularOICOvertime: 5,
        hoursSpecialHolidayOICOvertime: 5,
        hoursRegularHolidayOICOvertime: 5,
        hoursDoubleHolidayOICOvertime: 5,
        hoursWorkedOICNSD: 5,
        hoursSpecialHolidayOICNSD: 5,
        hoursRegularHolidayOICNSD: 5,
        hoursDoubleHolidayOICNSD: 5,
        hoursAbsent: 5,
        unallocated: 0,
      },
    ],
  },
  {
    id: 444,
    fullName: 'Employee Five',
    department: { id: 1, departmentName: 'department two' },
    logs: [
      {
        date: 0,
        scheduleStart: 0,
        scheduleEnd: 0,
        inTime: 0,
        outTime: 0,
        message: 0,
        isError: 0,
        late: 5,
        undertime: 5,
        worked: 5,
        hoursRestDay: 5,
        hoursSpecialHoliday: 5,
        hoursSpecialHolidayAndRestDay: 5,
        hoursRegularHoliday: 5,
        hoursRegularHolidayAndRestDay: 5,
        hoursDoubleHoliday: 5,
        hoursDoubleHolidayAndRestDay: 5,
        hoursRegularOvertime: 5,
        hoursRestOvertime: 5,
        hoursSpecialHolidayOvertime: 5,
        hoursSpecialHolidayAndRestDayOvertime: 5,
        hoursRegularHolidayOvertime: 5,
        hoursRegularHolidayAndRestDayOvertime: 5,
        hoursDoubleHolidayOvertime: 5,
        hoursDoubleHolidayAndRestDayOvertime: 5,
        hoursNightDifferential: 5,
        hoursWorkedNSD: 5,
        hoursRestDayNSD: 5,
        hoursSpecialHolidayNSD: 5,
        hoursSpecialHolidayAndRestDayNSD: 5,
        hoursRegularHolidayNSD: 5,
        hoursRegularHolidayAndRestDayNSD: 5,
        hoursDoubleHolidayNSD: 5,
        hoursDoubleHolidayAndRestDayNSD: 5,
        countDoubleHolidayAndRestDay: 5,
        workedOIC: 5,
        hoursSpecialHolidayOIC: 5,
        hoursRegularHolidayOIC: 5,
        hoursDoubleHolidayOIC: 5,
        hoursRegularOICOvertime: 5,
        hoursSpecialHolidayOICOvertime: 5,
        hoursRegularHolidayOICOvertime: 5,
        hoursDoubleHolidayOICOvertime: 5,
        hoursWorkedOICNSD: 5,
        hoursSpecialHolidayOICNSD: 5,
        hoursRegularHolidayOICNSD: 5,
        hoursDoubleHolidayOICNSD: 5,
        hoursAbsent: 5,
        unallocated: 0,
      },
    ],
  },
  {
    id: 555,
    fullName: 'Employee Six',
    department: { id: 1, departmentName: 'department two' },
    logs: [
      {
        date: 0,
        scheduleStart: 0,
        scheduleEnd: 0,
        inTime: 0,
        outTime: 0,
        message: 0,
        isError: 0,
        late: 5,
        undertime: 5,
        worked: 5,
        hoursRestDay: 5,
        hoursSpecialHoliday: 5,
        hoursSpecialHolidayAndRestDay: 5,
        hoursRegularHoliday: 5,
        hoursRegularHolidayAndRestDay: 5,
        hoursDoubleHoliday: 5,
        hoursDoubleHolidayAndRestDay: 5,
        hoursRegularOvertime: 5,
        hoursRestOvertime: 5,
        hoursSpecialHolidayOvertime: 5,
        hoursSpecialHolidayAndRestDayOvertime: 5,
        hoursRegularHolidayOvertime: 5,
        hoursRegularHolidayAndRestDayOvertime: 5,
        hoursDoubleHolidayOvertime: 5,
        hoursDoubleHolidayAndRestDayOvertime: 5,
        hoursNightDifferential: 5,
        hoursWorkedNSD: 5,
        hoursRestDayNSD: 5,
        hoursSpecialHolidayNSD: 5,
        hoursSpecialHolidayAndRestDayNSD: 5,
        hoursRegularHolidayNSD: 5,
        hoursRegularHolidayAndRestDayNSD: 5,
        hoursDoubleHolidayNSD: 5,
        hoursDoubleHolidayAndRestDayNSD: 5,
        countDoubleHolidayAndRestDay: 5,
        workedOIC: 5,
        hoursSpecialHolidayOIC: 5,
        hoursRegularHolidayOIC: 5,
        hoursDoubleHolidayOIC: 5,
        hoursRegularOICOvertime: 5,
        hoursSpecialHolidayOICOvertime: 5,
        hoursRegularHolidayOICOvertime: 5,
        hoursDoubleHolidayOICOvertime: 5,
        hoursWorkedOICNSD: 5,
        hoursSpecialHolidayOICNSD: 5,
        hoursRegularHolidayOICNSD: 5,
        hoursDoubleHolidayOICNSD: 5,
        hoursAbsent: 5,
        unallocated: 0,
      },
    ],
  },
];
