apiVersion: apps/v1
kind: Deployment
metadata:
  name: hr
  namespace: hr
  labels:
    app: hr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hr
  template:
    metadata:
      labels:
        app: hr
    spec:
      imagePullSecrets:
        - name: docker-ace
      containers:
        - name: hr
          image: docker.ace-mc-bohol.com/hr:3.0.34
          ports:
            - containerPort: 20000
---
apiVersion: v1
kind: Service
metadata:
  name: hr
  namespace: hr
  labels:
    app: hr
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 20000
      name: hr
  selector:
    app: hr
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lanexbot-ingress
  namespace: hr
  annotations:
    cert-manager.io/cluster-issuer: 'letsencrypt-prod'
spec:
  tls:
    - hosts:
        - hr.ace-mc-bohol.com
      secretName: hr-tls-secret
  rules:
    - host: hr.ace-mc-bohol.com
      http:
        paths:
          - pathType: Prefix
            path: '/'
            backend:
              service:
                name: hr
                port:
                  number: 20000
